"""Test the BatchRunner with injected fake S3 + Batch clients."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from src.cloud.batch_runner import BatchRunner
from src.cloud.manifest import ArrayManifest, JobManifest, JobStatus
from src.cloud.s3_io import LocalFSClient
from src.schemas.camera_track import CameraFrame, CameraTrack


class FakeBatch:
    """Stub batch client. Records submit_job calls and serves a scripted
    sequence of describe_jobs responses.
    """

    def __init__(self, describe_sequence: list[dict[str, Any]]) -> None:
        self.describe_sequence = describe_sequence
        self.describe_idx = 0
        self.submitted: list[dict[str, Any]] = []

    def submit_job(self, **kwargs: Any) -> dict[str, Any]:
        self.submitted.append(kwargs)
        return {"jobId": "fake-job-1"}

    def describe_jobs(self, **kwargs: Any) -> dict[str, Any]:
        idx = min(self.describe_idx, len(self.describe_sequence) - 1)
        self.describe_idx += 1
        return self.describe_sequence[idx]


@pytest.fixture
def fixture_output(tmp_path: Path) -> Path:
    out = tmp_path / "output"
    (out / "shots").mkdir(parents=True)
    (out / "camera").mkdir(parents=True)
    (out / "hmr_world").mkdir(parents=True)
    (out / "shots" / "play_01.mp4").write_bytes(b"stub mp4")
    cam = CameraTrack(
        clip_id="play_01",
        fps=30.0,
        image_size=(1280, 720),
        t_world=[0.0, 0.0, 22.0],
        frames=(
            CameraFrame(
                frame=0,
                K=[[1500.0, 0.0, 640.0], [0.0, 1500.0, 360.0], [0.0, 0.0, 1.0]],
                R=[[1.0, 0.0, 0.0], [0.0, 0.0, -1.0], [0.0, 1.0, 0.0]],
                confidence=1.0,
                is_anchor=True,
            ),
        ),
    )
    cam.save(out / "camera" / "play_01_camera_track.json")
    return out


def _stage_cfg(**overrides: Any) -> dict[str, Any]:
    cfg = {
        "runner": "batch",
        "device": "cpu",
        "checkpoint": "",
        "max_sequence_length": 120,
        "min_track_frames": 10,
        "theta_savgol_window": 11,
        "theta_savgol_order": 2,
        "root_slerp_window": 5,
        "ground_snap_velocity": 0.1,
        "root_t_savgol_window": 5,
        "root_t_savgol_order": 2,
        "lean_correction_deg": 0.0,
        "batch": {
            "region": "us-east-1",
            "s3_bucket": "test-bucket",
            "s3_prefix": "runs",
            "job_queue": "test-queue",
            "job_definition": "test-jobdef:1",
            "poll_seconds": 1,
            "job_timeout_seconds": 600,
            "max_concurrent_jobs": 24,
            "failure_policy": "continue",
        },
    }
    cfg.update(overrides)
    return cfg


def _completed_array(n: int) -> dict[str, Any]:
    return {
        "jobs": [
            {
                "jobId": "fake-job-1",
                "status": "SUCCEEDED",
                "arrayProperties": {
                    "statusSummary": {
                        "SUCCEEDED": n,
                        "FAILED": 0,
                        "RUNNING": 0,
                        "PENDING": 0,
                    },
                },
            },
        ],
    }


def _seed_handler_outputs(
    s3: LocalFSClient,
    run_root: str,
    specs: list[tuple[str, str]],
) -> None:
    """Pretend the in-container handler ran: write status.json + outputs
    for each (shot_id, player_id) the runner expects.
    """
    for shot_id, player_id in specs:
        output_prefix = f"{run_root}/jobs/{shot_id}__{player_id}"
        s3.upload_bytes(
            JobStatus(status="ok", duration_seconds=1.2, frames=20).to_json().encode("utf-8"),
            f"{output_prefix}/status.json",
        )
        s3.upload_bytes(b"fake-npz", f"{output_prefix}/output/{shot_id}__{player_id}_smpl_world.npz")
        s3.upload_bytes(b'{"frames": []}', f"{output_prefix}/output/{shot_id}__{player_id}_kp2d.json")


def test_batch_runner_submits_array_job_and_downloads(
    tmp_path: Path, fixture_output: Path,
) -> None:
    s3_root = tmp_path / "s3"
    s3 = LocalFSClient(root=s3_root)

    specs = [("play_01", "p001"), ("play_01", "p002")]
    ordered = [
        ((shot, player), [(0, (0, 0, 10, 10)), (1, (0, 0, 10, 10))])
        for shot, player in specs
    ]

    # Pre-seed handler outputs as if the array job already ran. We let
    # FakeBatch return SUCCEEDED immediately so the runner pulls them.
    # ``run_id`` is regenerated by BatchRunner — we capture it after the
    # fact via the output/.run_id file.

    cfg = _stage_cfg()
    runner = BatchRunner(
        cfg=cfg["hmr_world"] if "hmr_world" in cfg else cfg,
        output_dir=fixture_output,
        s3_client=s3,
        batch_client=FakeBatch([_completed_array(n=2)]),
    )

    # Need to seed outputs at the correct run_root. BatchRunner persists
    # the run_id at output/.run_id, so we pre-write it.
    (fixture_output / ".run_id").write_text("test-run-id")
    run_root = "s3://test-bucket/runs/test-run-id"
    _seed_handler_outputs(s3, run_root, specs)

    runner.run_tracks(
        ordered=ordered,
        camera_tracks_by_shot={},  # not consumed by the runner
        out_dir=fixture_output / "hmr_world",
    )

    # Verify the runner uploaded the shared inputs.
    expected_video = s3_root / "test-bucket" / "runs" / "test-run-id" / "shots" / "play_01.mp4"
    expected_camera = s3_root / "test-bucket" / "runs" / "test-run-id" / "camera" / "play_01_camera_track.json"
    assert expected_video.exists()
    assert expected_camera.exists()

    # Per-job manifest is written.
    job_manifest_path = (
        s3_root / "test-bucket" / "runs" / "test-run-id" / "jobs" / "play_01__p001" / "input.json"
    )
    assert job_manifest_path.exists()
    manifest = JobManifest.from_json(job_manifest_path.read_text())
    assert manifest.run_id == "test-run-id"
    assert manifest.shot_id == "play_01"
    assert manifest.player_id == "p001"

    # ArrayManifest exists with 2 entries.
    array_path = s3_root / "test-bucket" / "runs" / "test-run-id" / "jobs" / "array_index.json"
    array_manifest = ArrayManifest.from_json(array_path.read_text())
    assert len(array_manifest.entries) == 2

    # Outputs downloaded to local hmr_world dir.
    assert (fixture_output / "hmr_world" / "play_01__p001_smpl_world.npz").exists()
    assert (fixture_output / "hmr_world" / "play_01__p001_kp2d.json").exists()
    assert (fixture_output / "hmr_world" / "play_01__p002_smpl_world.npz").exists()


def test_batch_runner_aborts_on_failure_when_policy_is_abort(
    tmp_path: Path, fixture_output: Path,
) -> None:
    s3_root = tmp_path / "s3"
    s3 = LocalFSClient(root=s3_root)

    specs = [("play_01", "p001"), ("play_01", "p002")]
    ordered = [
        ((shot, player), [(0, (0, 0, 10, 10)), (1, (0, 0, 10, 10))])
        for shot, player in specs
    ]

    cfg = _stage_cfg()
    cfg["batch"]["failure_policy"] = "abort"

    runner = BatchRunner(
        cfg=cfg,
        output_dir=fixture_output,
        s3_client=s3,
        batch_client=FakeBatch([
            {
                "jobs": [
                    {
                        "jobId": "fake-job-1",
                        "status": "SUCCEEDED",
                        "arrayProperties": {
                            "statusSummary": {"SUCCEEDED": 1, "FAILED": 1},
                        },
                    },
                ],
            },
        ]),
    )

    (fixture_output / ".run_id").write_text("test-run-id")
    run_root = "s3://test-bucket/runs/test-run-id"

    # p001 succeeded, p002 failed (error status.json).
    s3.upload_bytes(
        JobStatus(status="ok", duration_seconds=1.0, frames=20).to_json().encode("utf-8"),
        f"{run_root}/jobs/play_01__p001/status.json",
    )
    s3.upload_bytes(b"fake-npz", f"{run_root}/jobs/play_01__p001/output/play_01__p001_smpl_world.npz")
    s3.upload_bytes(b'{"frames":[]}', f"{run_root}/jobs/play_01__p001/output/play_01__p001_kp2d.json")
    s3.upload_bytes(
        JobStatus(
            status="error", duration_seconds=2.0, frames=20,
            error_type="RuntimeError", error_message="OOM",
        ).to_json().encode("utf-8"),
        f"{run_root}/jobs/play_01__p002/status.json",
    )

    with pytest.raises(RuntimeError, match="failure_policy=abort"):
        runner.run_tracks(
            ordered=ordered,
            camera_tracks_by_shot={},
            out_dir=fixture_output / "hmr_world",
        )


def test_batch_runner_complains_about_missing_config(
    tmp_path: Path, fixture_output: Path,
) -> None:
    cfg = _stage_cfg()
    cfg["batch"]["s3_bucket"] = ""    # missing
    runner = BatchRunner(
        cfg=cfg,
        output_dir=fixture_output,
        s3_client=LocalFSClient(root=tmp_path / "s3"),
        batch_client=FakeBatch([_completed_array(n=1)]),
    )
    with pytest.raises(RuntimeError, match="s3_bucket"):
        runner.run_tracks(
            ordered=[(("play_01", "p001"), [(0, (0, 0, 10, 10))])],
            camera_tracks_by_shot={},
            out_dir=fixture_output / "hmr_world",
        )


def test_hmr_world_stage_dispatches_to_batch_runner(
    tmp_path: Path, monkeypatch,
) -> None:
    """When ``hmr_world.runner == 'batch'``, the stage builds a
    BatchRunner and calls ``run_tracks`` instead of looping in-process.
    """
    from src.schemas.tracks import Track, TrackFrame, TracksResult
    from src.stages.hmr_world import HmrWorldStage

    out = tmp_path / "output"
    (out / "shots").mkdir(parents=True)
    (out / "camera").mkdir(parents=True)
    (out / "tracks").mkdir(parents=True)
    (out / "shots" / "play_01.mp4").write_bytes(b"stub mp4")

    cam = CameraTrack(
        clip_id="play_01",
        fps=30.0,
        image_size=(1280, 720),
        t_world=[0.0, 0.0, 22.0],
        frames=(
            CameraFrame(
                frame=0,
                K=[[1500.0, 0.0, 640.0], [0.0, 1500.0, 360.0], [0.0, 0.0, 1.0]],
                R=[[1.0, 0.0, 0.0], [0.0, 0.0, -1.0], [0.0, 1.0, 0.0]],
                confidence=1.0,
                is_anchor=True,
            ),
        ),
    )
    cam.save(out / "camera" / "play_01_camera_track.json")
    tr = TracksResult(
        shot_id="play_01",
        tracks=[
            Track(
                track_id="T001",
                class_name="player",
                team="A",
                player_id="p001",
                player_name="",
                frames=[
                    TrackFrame(
                        frame=i,
                        bbox=[10, 20, 100, 200],
                        confidence=1.0,
                        pitch_position=None,
                    )
                    for i in range(15)
                ],
            ),
        ],
    )
    tr.save(out / "tracks" / "play_01_tracks.json")

    calls: list[dict[str, Any]] = []

    class _RunnerSpy:
        def __init__(self, *, cfg, output_dir):
            calls.append({"cfg": cfg, "output_dir": output_dir})

        def run_tracks(self, **kwargs):
            calls.append({"kind": "run_tracks", **kwargs})

    monkeypatch.setattr(
        "src.cloud.batch_runner.BatchRunner", _RunnerSpy, raising=False
    )

    cfg = {
        "hmr_world": {
            "runner": "batch",
            "device": "cpu",
            "min_track_frames": 10,
            "theta_savgol_window": 11,
            "theta_savgol_order": 2,
            "root_slerp_window": 5,
            "root_t_savgol_window": 5,
            "root_t_savgol_order": 2,
            "lean_correction_deg": 0.0,
            "ground_snap_velocity": 0.1,
            "batch": {
                "region": "us-east-1",
                "s3_bucket": "test-bucket",
                "s3_prefix": "runs",
                "job_queue": "q",
                "job_definition": "d:1",
                "poll_seconds": 1,
                "max_concurrent_jobs": 24,
                "failure_policy": "continue",
            },
        },
    }
    stage = HmrWorldStage(config=cfg, output_dir=out)
    stage.run()

    # First call: ctor; second: run_tracks.
    assert len(calls) == 2
    assert calls[0]["output_dir"] == out
    assert calls[0]["cfg"]["runner"] == "batch"
    rt = calls[1]
    assert rt["kind"] == "run_tracks"
    assert any(player == "p001" for (_, player), _ in rt["ordered"])
